### PR TITLE
Dependency container action bug

### PR DESCRIPTION
**Pull request by ali-raza-saleem**

### CODE REVIEW

**Comment by mehrancodes** [comment]
@alexwenzel @the-alichemist could you resolve conflicts and merge if possible?

**Comment by ganapatimoger** [comment]
There is error while doing some actions on resources having this package installed. If I remove the package the actions are working fine. Please fix this issue  @alexwenzel  @the-alichemist

**Comment by ganapatimoger** [comment]
please merge this fix

**Comment by skeylup** [comment]
yes please !

**Comment by mehrancodes** [comment]
You can use version dev-master until they add tag for this change

**Comment by alexwenzel** [comment]
Will fix this the next day.

**Comment by alexwenzel** [comment]
> There is error while doing some actions on resources having this package installed. If I remove the package the actions are working fine. Please fix this issue @alexwenzel @the-alichemist

I merged this PR. Does it fix your issue?
if not, please open a new PR and describe your problem.

**Comment by alexwenzel** [comment]
> There is error while doing some actions on resources having this package installed. If I remove the package the actions are working fine. Please fix this issue @alexwenzel @the-alichemist

i think i fixed it. pull master branch again.

**Comment by cloudstorydev** [comment]
Hi, sorry to use this channel. But I tested  found issue with BelongsTo inside the DependencyContainer, it does not show the options. I compared with plain BelongsTo, the different is in the network request. (Network request failed when inside DependencyContainer)

**BelongsTo - Inside DependencyContainer:** 
- first: false
- search: 
- withTrashed: false
- editing: true
- editMode: create

**BelongsTo - Plain:**
- first: false
- search: 
- withTrashed: false
- viaResource: 
- viaResourceId: 
- viaRelationship: 
- editing: true
- editMode: create

**Pull request merged**
